### PR TITLE
Update to the latest version of Poetry

### PR DESCRIPTION
**Pull request by macbre**
https://github.com/python-poetry/poetry/releases/tag/1.1.6

### CODE REVIEW

**Comment by sondrelg** [comment]
Nice 👏 Thanks @macbre!

Would you mind also updating the readme, etc. like in #26?

**Comment by macbre** [comment]
@sondrelg - updated in 0551681.

**Comment by sondrelg** [comment]
If you're still on we also need to update the requirements.txt and all the code example if possible. See the PR I linked if you want to do it.

If not I can merge this and finish it in a few hours before releasing a new version :)

**Comment by macbre** [comment]
@sondrelg - `requirements.txt` dependency bumped in 8a29ddd.

I'm not sure about the code examples, though. Should I assume `v1.1.3` will be the next version of `snok/install-poetry` action?

**Review by sondrelg — APPROVED** [review]

**Pull request merged**
