### PR TITLE
feat: Add `install-path` action output

### PR DESCRIPTION
**Pull request by sondrelg**

### CODE REVIEW

**Comment by miigotu** [comment]
Would be a cool experiment to see if we can make an action that installs poetry, and then uses the installed version --help output to generate yml for inputs, and PR it back to master. That way the inputs are always supported for the latest version automatically.

**Comment by sondrelg** [comment]
Yeah I'm sure you could even use `poetry config --list` to set the inputs. I guess the installation script URL should be static now that Poetry has moved the installation script to a dedicated repo as well. Don't think we do anything different, wrt. to configuration, depending on OS or anything like that. 

The only thing I'm not sure about is whether you would want to always stay up to date. A breaking change in Poetry should probably result in a breaking change in the action; especially because we re-tag v1, not just v1.X.X. Looking at v1.2.0 it seems to break quite a lot of things.

**Comment by miigotu** [comment]
I think you could tag you install-poetry as the same version as poetry, and remove the poetry version input. Then `uses: snok/install-poetry@1.1.13` would install that version of poetry and the inputs would always match that version of poetry completely.

**Comment by miigotu** [comment]
I think you could tag you install-poetry as the same version as poetry, and remove the poetry version input. Then `uses: snok/install-poetry@1.1.13` would install that version of poetry and the inputs would always match that version of poetry completely. 

And what I mean about always being up to date is the inputs always matching whatever version of poetry you decide to use in the action using install-poetry, instead of us always having to add new inputs or remove or rename them when they change upstream, and possibly not working with the selected poetry.

**Pull request closed without merging**
