### PR TITLE
Add option for installer.parallel and bump default poetry to 1.1.8

### PR DESCRIPTION
**Pull request by miigotu**
Add ability to set installer.parallel config option with action arguments.
Bump default poetry version to 1.1.8, which fixes bugs related to requirements markers that contain "platform_machine"

Signed-off-by: miigotu <miigotu@gmail.com>

### CODE REVIEW

**Comment by sondrelg** [comment]
This looks great @miigotu 👍 

The tests fail with `python3: can't open file '1.1.8': [Errno 2] No such file or directory
/tmp/tmp.NjpME7uoRs: line 35: poetry: command not found`, but I believe that's because it's pulling the script from the main branch in the `action.yml`. 

Can you replace `curl -sSL https://raw.githubusercontent.com/snok/install-poetry/main/scripts/v1.2/main.sh` with `curl -sSL https://raw.githubusercontent.com/miigotu/install-poetry/installer-parallel/scripts/v1.2/main.sh` to run the tests from your fork; then when they successfully pass, make another commit to change it back?

Or if you have another suggestion for how to use the local script directly instead of curling in tests, that would work too 👍

**Comment by sondrelg** [comment]
Since this is adding new functionality, we should also probably create a new `1.3` script instead of changing the `1.2` script in place; otherwise older versions of the action will break.

**Comment by miigotu** [comment]
> Since this is adding new functionality, we should also probably create a new `1.3` script instead of changing the `1.2` script in place; otherwise older versions of the action will break.

Sure can

**Comment by miigotu** [comment]
@sondrelg I'm not sure a 1.3 is needed, because no functionality is removed and the new option is not required, it defaults to the default behavior of poetry as it was before. If you still want me to I can leave it in 1.3, or I can eliminate the extra code and revert this back to 1.2

**Comment by sondrelg** [comment]
Since we're adding a new argument to the script, I think this will still break old version of the action since those versions will only pass `n-1` arguments while the new script would have `n` arguments - does that make sense?

So I think we should probably create a copy of `v1.2` called `v1.3` in a new folder etc, and add the new argument there.

I see you're making changes now so I'll let you push everything before reviewing 🙂 Just let me know when you want me to take a look! And let me know if you disagree with the above 😛

**Comment by miigotu** [comment]
Yeah I made the requested changed, but my thoughts were that if they were using as @v1.6, that action.yml __should__ be pulling https://raw.githubusercontent.com/snok/install-poetry/v1.1.6/scripts/v1.2/main.sh rather than main how it is now, so no matter which version a project uses, it will always pull the correct script for that version without having to have multiple copies of the script in the repo, if that makes sense?  We could make tags always pull the script that is part of that tagged commit.

Should we try and go down that road or leave it with a 1.3?

**Comment by miigotu** [comment]
Could you approve the workflow to run, please?

**Comment by sondrelg** [comment]
Yeah that would be really nice if we could make it work! Having to be _this_ careful with the main branch is annoying 😄

**Comment by miigotu** [comment]
> Yeah that would be really nice if we could make it work! Having to be _this_ careful with the main branch is annoying 
> 
> EDIT: I guess we wouldn't really need the same script versioning going forward if we switched to relative script fetching. Maybe we could just add a new script called `configure_poetry.sh` or something in the script folder instead of the v1.3 naming?

Technically we could eliminate the sh script entirely, and write steps right in action.yml with the shell parameter, one step for windows, one for unix. Then no curl is needed at all, since it would be pulled in with the uses: directive.  I think that should be worked on separately in a different branch, and tagged as an alpha while we work on it. It should be heavily scrutinized and tested for awhile before making such a change.

**Comment by sondrelg** [comment]
> Technically we could eliminate the sh script entirely, and write steps right in action.yml with the shell parameter, one step for windows, one for unix. Then no curl is needed at all, since it would be pulled in with the uses: directive. I think that should be worked on separately in a different branch, and tagged as an alpha while we work on it. It should be heavily scrutinized and tested for awhile before making such a change.

Yeah great point - that'll be much easier to maintain going forward 👏

I can attempt to do that now, and let you rebase on the main branch after?

**Comment by sondrelg** [comment]
I merged the changes @miigotu 🙂 Think this is ready for a rebase rebase, then we can merge the new option + updated readme changes before releasing `v1.2` 🚀

**Comment by miigotu** [comment]
I'll try and get it done a bit later today. Great work.

**Comment by sondrelg** [comment]
Let me know if you'd prefer me to help you finish this @miigotu 👍 I've got some time today, so if you're busy I'd be happy to help 🙂

**Comment by miigotu** [comment]
Yeah I'm perfectly fine with you taking over on this. I don't know when I will have time next to get my laptop out. A lot going on, two of my kids are playing football and starting school and bunch of other stuff right now. I can try and look over whatever you put together though.

**Comment by sondrelg** [comment]
Closing in favor of https://github.com/snok/install-poetry/pull/51

**Pull request closed without merging**
