### PR TITLE
Test against Python 3.10.0-alpha.5

### PR DESCRIPTION
**Pull request by macbre**
Re-apply #25 // @sondrelg

### CODE REVIEW

**Comment by macbre** [comment]
```
Run ./
/tmp/tmp.UNw8QVrbnh: line 1: 404:: command not found
Error: Process completed with exit code 127.
```

Getting strange error on CI runs - @sondrelg ?

**Comment by sondrelg** [comment]
Of course there is 

giphy (1)

I'll take a look

**Comment by sondrelg** [comment]
Fix incoming 😊 Should be OK in ~30 mins

**Comment by sondrelg** [comment]
If you rebase on main again it *should* pass 🤞 Or at least it shouldn't fail with the same error 😄

**Comment by macbre** [comment]
Great! So we're waiting for a Poetry non-alpha release now?

**Comment by sondrelg** [comment]
Yeah as long as nothing else comes up that needs fixing, I guess updating the latest default version is next, when 1.2 is released 🙂

**Comment by JWCook** [comment]
@sondrelg Confirmed working with python 3.10.0-beta.1, poetry 1.2.0a1, and install-poetry 1.1.6 in these three projects:
* https://github.com/reclosedev/requests-cache/runs/2650966112
* https://github.com/JWCook/aiohttp-client-cache/runs/2651094750
* https://github.com/niconoe/pyinaturalist/runs/2651120423

**Comment by sondrelg** [comment]
Thanks a bunch @JWCook  👏

**Pull request merged**
