### PR TITLE
Test against Python 3.10.0-alpha.5

### PR DESCRIPTION
**Pull request by macbre**
@sondrelg - I guess it's worth testing against the upcoming Python version.

### CODE REVIEW

**Comment by sondrelg** [comment]
Yeah 100%. The question, I guess, is whether it's an action issue or a Poetry issue when it fails 😅  Think I opened a similar PR a few weeks back and when the workflows failed, just figured I'd wait until the official release.

Feel free to tinker with this to see if there's anything that can be done on the action side of things 👏

**Comment by macbre** [comment]
https://github.com/snok/install-poetry/pull/25/checks?check_run_id=2030658818

```
ModuleNotFoundError: No module named 'cleo'
```

I get a quite similar error. You're right, it looks like something that needs to be fixed on `poetry` side.

**Comment by sondrelg** [comment]
Yeah looks like even 1.1.5 fails against Python 3.10 🤷‍♂️

**Comment by JWCook** [comment]
I also just ran into this on with 3.10.0-beta.1. There are several issues and threads out there regarding this same error but with previous python versions. See https://github.com/python-poetry/poetry/issues/553 and https://github.com/python-poetry/poetry/issues/3345. It appears to be an issue with packages vendored by poetry, with a number of possible workarounds proposed in those linked issues. I'm not sure which of those (if any) would be the cleanest option to use here.

**Comment by sondrelg** [comment]
If you've run into this issue using the action, this sounds like a good time to pick this PR back up and try to resolve it 🙂  Thanks for letting us know!

Are you running Poetry on 3.10.0-beta.1 outside of Github's runners @JWCook? Do we know if that works? I would imagine it does, but it seems like a good thing to make sure of before we dive into this properly - if you haven't run it on 3.10 I could test this myself

Looking at the threads you linked, I see the issues seem to be rooted in reinstalling Poetry which I wouldn't expect to be an issue here tbh, but there's no harm in testing the suggested workarounds anyway 👏

**Comment by macbre** [comment]
@sondrelg - rebased to v1.2 version branch (#33)

**Comment by sondrelg** [comment]
Not sure how I closed this - wasn't my intention @macbre, sorry 🙏 If you reopen I will merge

**Comment by sondrelg** [comment]
Just point it at main🙂

**Comment by macbre** [comment]
I do not have option to reopen this PR... I'll apply my change once again then.

**Pull request closed without merging**
