### PR TITLE
Clean up workflows

### PR DESCRIPTION
**Pull request by sondrelg**
Updates versions and purges a few tests. Also notably removes the old scripts needed to run the workflow for tags < 1.2.

It has been 18 months since v1.2 was released and the readme-examples have always used the `@v1` tag. The workflow likely didn't have many users before this, so I doubt many if any will be affected by this.

@miigotu what do you think. It's not ideal, but it would be really nice to get rid of these. The old-script test is now also failing randomly, which is what made now seem like a good time :)

### CODE REVIEW

**Comment by miigotu** [comment]
I generally only test for the current version in my projects. The test for previous versions exist on the git at the tagged commit, so there is no need to keep them around imo.

**Comment by sondrelg** [comment]
IIRC we explicitly would fetch from the repo no the `main` branch in earlier versions, so it wasn't actually tied to the git version. That changed in v1.2 which we pushed in September 2021. Think I'll go ahead anyway, hoping no one will be affected :crossed_fingers: Anyone affected should be able to just change from `v1.1.x` to `v.1.2.x` or `v1.3.x` to fix it.

**Comment by gitonthescene** [comment]
This just [bit me](https://github.com/gitonthescene/csv-reconcile/pull/93) FWIW.  I’m not complaining.  It should be easy enough to fix.  Rather, is there a preferred way to stay up-to-date?  Should I just follow the project?

I’m not a super active user and mostly use this with buildbot pr’s.

**Comment by sondrelg** [comment]
Sorry @gitonthescene :bow: We just made poor design decisions for the version < 1.2. Won't happen again. If you change the tag to `v1` or `v1.3.3` it should work going forwards

**Comment by gitonthescene** [comment]
Really no worries at all.  I changed it to `v1` and that seemed to work.  If there's something else I should be doing, please let me know.

**Pull request merged**
